name: cam
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - ca-certificates=2025.12.2
  - ld_impl_linux-64=2.40
  - libffi=3.4.4
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libgomp=15.2.0
  - libstdcxx=15.2.0
  - libstdcxx-ng=15.2.0
  - ncurses=6.4
  - ninja=1.13.1
  - ninja-base=1.13.1
  - openssl=3.0.18
  - pip=25.1
  - python=3.9.21
  - readline=8.2
  - setuptools=78.1.1
  - sqlite=3.45.3
  - tk=8.6.14
  - wheel=0.45.1
  - xz=5.6.4
  - zlib=1.2.13
  - pip:
      - bayesian-optimization==1.4.0
      - beautifulsoup4==4.14.3
      - boto3==1.42.24
      - botocore==1.42.24
      - certifi==2025.7.9
      - cffi==1.17.1
      - charset-normalizer==3.4.2
      - click==8.1.8
      - cma==4.4.1
      - contourpy==1.3.0
      - cryptography==44.0.3
      - cycler==0.12.1
      - directsearch==1.0
      - filelock==3.18.0
      - fire==0.7.0
      - flwr==1.19.0
      - fonttools==4.58.1
      - freia==0.2
      - fsspec==2025.5.1
      - gdown==5.2.0
      - grad-cam==1.5.5
      - grpcio==1.64.3
      - hatchling==1.27.0
      - idna==3.10
      - imageio==2.37.0
      - importlib-resources==6.5.2
      - iterators==0.0.2
      - jinja2==3.1.6
      - jmespath==1.0.1
      - joblib==1.5.1
      - kiwisolver==1.4.7
      - lazy-loader==0.4
      - lpips==0.1.4
      - markdown-it-py==3.0.0
      - markupsafe==3.0.2
      - matplotlib==3.9.4
      - mdurl==0.1.2
      - medmnist==3.0.2
      - mpmath==1.3.0
      - networkx==3.2.1
      - nevergrad==1.0.12
      - numpy==2.0.2
      - nvidia-cublas-cu12==12.6.4.1
      - nvidia-cuda-cupti-cu12==12.6.80
      - nvidia-cuda-nvrtc-cu12==12.6.77
      - nvidia-cuda-runtime-cu12==12.6.77
      - nvidia-cudnn-cu12==9.5.1.17
      - nvidia-cufft-cu12==11.3.0.4
      - nvidia-cufile-cu12==1.11.1.6
      - nvidia-curand-cu12==10.3.7.77
      - nvidia-cusolver-cu12==11.7.1.2
      - nvidia-cusparse-cu12==12.5.4.2
      - nvidia-cusparselt-cu12==0.6.3
      - nvidia-nccl-cu12==2.26.2
      - nvidia-nvjitlink-cu12==12.6.85
      - nvidia-nvtx-cu12==12.6.77
      - opacus==1.5.4
      - opencv-python==4.11.0.86
      - opt-einsum==3.4.0
      - packaging==25.0
      - pandas==2.3.0
      - pathspec==0.12.1
      - pillow==11.2.1
      - pluggy==1.6.0
      - protobuf==4.25.8
      - pycparser==2.22
      - pycryptodome==3.23.0
      - pygments==2.19.2
      - pyparsing==3.2.3
      - pysocks==1.7.1
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - pyyaml==6.0.2
      - requests==2.32.4
      - rich==13.9.4
      - s3transfer==0.16.0
      - scikit-image==0.24.0
      - scikit-learn==1.6.1
      - scipy==1.13.1
      - shellingham==1.5.4
      - six==1.17.0
      - soupsieve==2.8.1
      - sympy==1.14.0
      - termcolor==3.1.0
      - threadpoolctl==3.6.0
      - tifffile==2024.8.30
      - tomli==2.2.1
      - tomli-w==1.2.0
      - torch==2.7.0
      - torchaudio==2.7.0
      - torchvision==0.22.0
      - tqdm==4.67.1
      - triton==3.3.0
      - trove-classifiers==2025.5.9.12
      - ttach==0.0.3
      - typer==0.12.5
      - typing-extensions==4.13.2
      - tzdata==2025.2
      - urllib3==1.26.20
      - zipp==3.22.0
